server:
  port: 8091

spring:
  application:
    name: ACCOUNT-SERVICE
  #zipkin:
    #base-url: http://127.0.0.1:9411/


eureka:
  instance:
    preferIpAddress: true
    #hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      defaultZone: http://localhost:8761/eureka/ # Replace with your Eureka server URL